### ISSUE TITLE
More space between messages would look better.

### ISSUE THREAD

**Issue by saeidscorp** [NXij/tdesktop-dark#1]
It's really a great patch for Telegram. I love this dark theme.

However this last update has cramped all adjacent messages together. They seem dense to me.

Is that intentional or what?!

Thanks.

**Comment by NXij** [comment]
Yep, intentional.

I found that the telegram changes done previously created some confusion (atleast for me). It was already quite a long time ago, but in group chats the continuous messages were made so that the display picture is no longer on the side of every message, but on the side of the message so-to-say "blocks", in case the same author sent multiple messages in a row. And because of the messages all having almost the same margins between them, this created confusion in being able to easily distinct the sender of the messeges (atleast for me).

So I decided I group the messages together in a more understandable "block". It also looks modern with non-rounded edges.

It will take some time to get used to, but I think the change I made is positive, especially in environments where new messages come in at a very fast pace.

If you want to revert this change, you can edit the line 831 (msgMarginTopAttached: 0px;) in the basic.style file to correspond to your preferred margin.

**Comment by dmnmsc** [comment]
I get your point of view, NXij. But is a bit confusing when sending, in example, two pictures. They seem to be just one picture on chat. I think it would be better do something like WhatsApp does on Windows (less space betweeen same sender's messages, but still a tiny space). 

Will look better as well if the "agrouped" messages were using just one bubble (same bubble size for agrouped messages).

But this is jut an oppinion! I love your Telegram version, btw.
